import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata = {
  title:
    "Ali Abdo - Front-End Developer and Machine Learning Enthusiast",
  description:
    "I'm Ali Abdo, a passionate Front-End Developer and Machine Learning Enthusiast specializing in React.js, Next.js, and creating dynamic, scalable web solutions.",
  keywords:
    "Ali Abdo, Front-End Developer, Machine Learning, React.js, Next.js, JavaScript, Python",
  author: "Ali Abdo",
  robots: "index, follow",
  og: {
    title:
      "Ali Abdo - Front-End Developer and Machine Learning Enthusiast",
    description:
      "I'm Ali Abdo, a passionate Front-End Developer and Machine Learning Enthusiast specializing in React.js, Next.js, and creating dynamic, scalable web solutions.",
    image: "/me2.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
